export {
  ADMIN_ROLE_KEY,
  BUSINESS_SUCCESS_CODE,
  DEFAULT_CLIENT_ID,
  EnableStatus,
  type LanguageOption,
  LOGIN_PATH,
  SUPERADMIN_ROLE_ID,
  SUPERADMIN_ROLE_KEY,
  SUPERADMIN_USER_ID,
  SUPPORT_LANGUAGES,
  UNAUTHORIZED_CODE,
  YesNo,
} from './core';
export { DictEnum, type DictEnumKey } from './dict-enum';
export {
  CSS_VARIABLE_LAYOUT_CONTENT_HEIGHT,
  CSS_VARIABLE_LAYOUT_CONTENT_WIDTH,
  CSS_VARIABLE_LAYOUT_HEADER_HEIGHT,
  DEFAULT_NAMESPACE,
  ELEMENT_ID_MAIN_CONTENT,
} from './globals';
