#!/usr/bin/env bash
# In-container hot update for grokcli-2api.
# Requires:
#   - /var/run/docker.sock mounted into this container
#   - docker CLI available in PATH (image installs a static docker client)
# Optional (recommended for compose stacks):
#   - project dir mounted at GROK2API_COMPOSE_DIR (default /compose)
#
# Invoked by Go admin hot-update with env:
#   GROK2API_UPDATE_TAG / GROK2API_UPDATE_IMAGE
# Or args: $1=tag $2=image
#
# Steps:
#   1) docker pull IMAGE:TAG
#   2) if compose project present → compose up -d --force-recreate SERVICE
#   3) else recreate this container by id/name (best-effort)

set -euo pipefail

log() { echo "[g2a-hot-update $(date '+%F %T')] $*"; }

TAG="${1:-${GROK2API_UPDATE_TAG:-latest}}"
IMAGE="${2:-${GROK2API_UPDATE_IMAGE:-${GROK2API_GHCR_IMAGE:-ghcr.io/hm2899/grokcli-2api}}}"
TAG="${TAG#v}"
[[ -n "$TAG" ]] || TAG="latest"
[[ -n "$IMAGE" ]] || IMAGE="ghcr.io/hm2899/grokcli-2api"

SERVICE="${GROK2API_DOCKER_SERVICE:-grokcli-2api}"
COMPOSE_DIR="${GROK2API_COMPOSE_DIR:-/compose}"
OVERRIDE_FILE="${GROK2API_COMPOSE_OVERRIDE:-docker-compose.hot-update.yml}"
SOCK="${DOCKER_HOST:-unix:///var/run/docker.sock}"
SOCK_PATH="/var/run/docker.sock"
if [[ "$SOCK" == unix://* ]]; then
  SOCK_PATH="${SOCK#unix://}"
fi

if [[ ! -S "$SOCK_PATH" ]]; then
  log "error: docker socket not found at $SOCK_PATH (mount -v /var/run/docker.sock:/var/run/docker.sock)"
  exit 2
fi

if ! command -v docker >/dev/null 2>&1; then
  log "error: docker CLI not found in container PATH"
  exit 3
fi

# Resolve full image ref
if [[ "$IMAGE" == *@* ]]; then
  FULL="$IMAGE"
elif [[ "$IMAGE" == *:* && "$IMAGE" != *://* ]]; then
  if [[ "$TAG" != "latest" && "$IMAGE" != *":$TAG" ]]; then
    FULL="${IMAGE%%:*}:${TAG}"
  else
    FULL="$IMAGE"
  fi
else
  FULL="${IMAGE}:${TAG}"
fi

log "pull ${FULL}"
docker pull "$FULL"

compose_files=()
if [[ -f "${COMPOSE_DIR}/docker-compose.yml" ]]; then
  compose_files+=(-f docker-compose.yml)
  if [[ -f "${COMPOSE_DIR}/docker-compose.override.yml" ]]; then
    compose_files+=(-f docker-compose.override.yml)
  fi
  # Pin service image via ephemeral override so pull/up target the requested tag.
  cat >"${COMPOSE_DIR}/${OVERRIDE_FILE}" <<YAML
# Auto-generated by g2a-hot-update-incontainer — do not edit by hand.
services:
  ${SERVICE}:
    image: ${FULL}
    pull_policy: always
YAML
  compose_files+=(-f "${OVERRIDE_FILE}")
  log "compose project at ${COMPOSE_DIR}; service=${SERVICE}"
  cd "$COMPOSE_DIR"
  # shellcheck disable=SC2086
  docker compose "${compose_files[@]}" pull "$SERVICE"
  # shellcheck disable=SC2086
  docker compose "${compose_files[@]}" up -d --force-recreate --remove-orphans "$SERVICE"
  # shellcheck disable=SC2086
  docker compose "${compose_files[@]}" ps "$SERVICE" || true
  log "done: compose force-recreate ${SERVICE} -> ${FULL}"
  exit 0
fi

# Fallback: recreate this container by name/id (no compose project mounted).
CID="${GROK2API_DOCKER_CONTAINER:-}"
if [[ -z "$CID" ]]; then
  # hostname is often the short container id
  CID="$(hostname 2>/dev/null || true)"
fi
if [[ -z "$CID" ]]; then
  log "error: no compose project at ${COMPOSE_DIR} and cannot resolve container id"
  exit 4
fi

log "no compose project; recreating container ${CID} with image ${FULL}"
# Inspect existing container for restart-equivalent recreate via docker CLI.
if ! docker inspect "$CID" >/dev/null 2>&1; then
  log "error: container ${CID} not found via docker inspect"
  exit 5
fi

NAME="$(docker inspect -f '{{.Name}}' "$CID" | sed 's#^/##')"
# Rename old container, create replacement with same config, start new, remove old.
STAMP="$(date +%s)"
OLD_NAME="${NAME}-old-${STAMP}"
log "rename ${NAME} -> ${OLD_NAME}"
docker rename "$CID" "$OLD_NAME"

# docker container create --image replaces image while reusing most settings via --volumes-from
# and network reconnect. Prefer: create from inspect JSON is complex; use:
#   docker run with --volumes-from and same network — incomplete.
# Safer compose-less path: docker update cannot change image. Use:
#   docker commit is wrong. Use recreate via:
#   docker create $(docker inspect ...)
# Minimal robust path for compose-less: stop + run with same name using image,
# re-attaching published ports from inspect.

python3 - "$OLD_NAME" "$FULL" "$NAME" <<'PY'
import json, subprocess, sys, shlex

old, image, name = sys.argv[1:4]
raw = subprocess.check_output(["docker", "inspect", old], text=True)
info = json.loads(raw)[0]
cfg = info.get("Config") or {}
host = info.get("HostConfig") or {}
net = info.get("NetworkSettings") or {}

cmd = ["docker", "create", "--name", name, "--restart", (host.get("RestartPolicy") or {}).get("Name") or "unless-stopped"]

# env
for e in cfg.get("Env") or []:
    cmd += ["-e", e]

# binds
for b in host.get("Binds") or []:
    cmd += ["-v", b]

# port bindings
ports = (host.get("PortBindings") or {})
for container_port, binds in ports.items():
    for b in binds or []:
        hp = b.get("HostPort") or ""
        hip = b.get("HostIp") or ""
        if hip and hip not in ("0.0.0.0", ""):
            cmd += ["-p", f"{hip}:{hp}:{container_port}"]
        elif hp:
            cmd += ["-p", f"{hp}:{container_port}"]
        else:
            cmd += ["-p", container_port]

# privileged / shm / security
if host.get("Privileged"):
    cmd.append("--privileged")
if host.get("ShmSize"):
    cmd += ["--shm-size", str(host["ShmSize"])]
for opt in host.get("SecurityOpt") or []:
    cmd += ["--security-opt", opt]

# networks (connect after create for non-default)
networks = list((net.get("Networks") or {}).keys())
# Image + command
cmd.append(image)
# Keep original entrypoint/cmd if present
ep = cfg.get("Entrypoint")
if ep:
    # docker create --entrypoint only takes first token form; leave default from image
    pass
# Don't override CMD — image entrypoint handles it.

print("+", " ".join(shlex.quote(c) for c in cmd), flush=True)
subprocess.check_call(cmd)
new_id = subprocess.check_output(["docker", "inspect", "-f", "{{.Id}}", name], text=True).strip()

# Attach extra networks
for n in networks:
    if n in ("bridge", "host", "none"):
        continue
    try:
        subprocess.check_call(["docker", "network", "connect", n, new_id])
    except subprocess.CalledProcessError as e:
        print(f"warn: network connect {n}: {e}", flush=True)

subprocess.check_call(["docker", "start", name])
# Stop and remove old
try:
    subprocess.call(["docker", "stop", "-t", "20", old])
except Exception:
    pass
try:
    subprocess.call(["docker", "rm", "-f", old])
except Exception:
    pass
print(f"recreated {name} from {old} using {image}", flush=True)
PY

log "done: container recreated -> ${FULL}"
