#!/usr/bin/env bash
# LEGACY host-side hot-update watcher for grokcli-2api.
# Prefer in-container mode (docker.sock + scripts/g2a-hot-update-incontainer.sh).
# Only needed when GROK2API_HOT_UPDATE_MODE=request_file.
# Polls data/update.request written by the admin UI, then:
#   1) retarget compose image to GHCR tag (when G2A_USE_GHCR=1 or request image set)
#   2) docker compose pull
#   3) docker compose up -d --force-recreate  (always restarts the service)
#
# Usage (host):
#   export G2A_COMPOSE_DIR=/root/grokcli-2api
#   export G2A_DATA_DIR=/var/lib/grokcli-2api/data
#   ./scripts/g2a-update-watcher.sh
#
# Optional env:
#   G2A_POLL_SEC=5
#   G2A_SERVICE=grokcli-2api
#   G2A_USE_GHCR=1              # default 1: write override image to GHCR tag
#   G2A_IMAGE=ghcr.io/hm2899/grokcli-2api
#   G2A_OVERRIDE_FILE=docker-compose.hot-update.yml

set -euo pipefail

COMPOSE_DIR="${G2A_COMPOSE_DIR:-/root/grokcli-2api}"
DATA_DIR="${G2A_DATA_DIR:-/var/lib/grokcli-2api/data}"
POLL_SEC="${G2A_POLL_SEC:-5}"
SERVICE="${G2A_SERVICE:-grokcli-2api}"
USE_GHCR="${G2A_USE_GHCR:-1}"
DEFAULT_IMAGE="${G2A_IMAGE:-ghcr.io/hm2899/grokcli-2api}"
OVERRIDE_FILE="${G2A_OVERRIDE_FILE:-docker-compose.hot-update.yml}"
REQ_FILE="${DATA_DIR}/update.request"
STATUS_FILE="${DATA_DIR}/update.status"

log() { echo "[g2a-update $(date '+%F %T')] $*"; }

write_status() {
  local status="$1" message="$2" tag="${3:-}" image="${4:-}"
  local now= finished=
  now=$(date +%s)
  if [[ "$status" == "done" || "$status" == "error" ]]; then
    finished="\"finished_at\": $now,"
  fi
  # Prefer python for safe JSON string escaping.
  python3 - "$STATUS_FILE" "$status" "$message" "$tag" "$image" "$now" "${finished:-}" <<'PY'
import json, sys, pathlib
path, status, message, tag, image, now, finished = sys.argv[1:8]
obj = {
  "tag": tag,
  "image": image,
  "requested_at": int(now),
  "status": status,
  "message": message,
}
if finished.strip():
    # finished_at already provided as fragment; set explicitly
    obj["finished_at"] = int(now)
pathlib.Path(path).write_text(json.dumps(obj, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
PY
}

write_override() {
  local full_image="$1"
  local path="${COMPOSE_DIR}/${OVERRIDE_FILE}"
  cat >"$path" <<YAML
# Auto-generated by g2a-update-watcher — do not edit by hand.
# Points ${SERVICE} at a GHCR release image for hot-update.
services:
  ${SERVICE}:
    image: ${full_image}
    pull_policy: always
YAML
  log "wrote override $path -> image ${full_image}"
}

compose() {
  # shellcheck disable=SC2086
  if [[ -f "${COMPOSE_DIR}/${OVERRIDE_FILE}" ]]; then
    docker compose -f docker-compose.yml -f docker-compose.override.yml -f "${OVERRIDE_FILE}" "$@"
  elif [[ -f "${COMPOSE_DIR}/docker-compose.override.yml" ]]; then
    docker compose -f docker-compose.yml -f docker-compose.override.yml "$@"
  else
    docker compose "$@"
  fi
}

run_update() {
  local req_path="$1"
  local tag image full
  tag=$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1])).get("tag") or "latest")' "$req_path")
  image=$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1])).get("image") or "")' "$req_path")
  tag="${tag#v}"
  [[ -n "$tag" ]] || tag="latest"
  [[ -n "$image" ]] || image="$DEFAULT_IMAGE"
  # image may already include :tag — still prefer requested tag when not a digest ref.
  if [[ "$image" == *:* && "$image" != *://* ]]; then
    if [[ "$image" == *@* ]]; then
      full="$image"
    elif [[ "$tag" != "latest" && "$image" != *":$tag" ]]; then
      base="${image%%:*}"
      full="${base}:${tag}"
    else
      full="$image"
    fi
  else
    full="${image}:${tag}"
  fi

  log "update request: full_image=$full (tag=$tag)"
  write_status "running" "pulling + recreating ${full}" "$tag" "$full"

  cd "$COMPOSE_DIR"

  if [[ "$USE_GHCR" == "1" ]]; then
    write_override "$full"
  fi

  set +e
  out=$(
    {
      echo ">>> docker compose pull ${SERVICE}"
      compose pull "$SERVICE" 2>&1
      echo ">>> docker compose up -d --force-recreate --remove-orphans ${SERVICE}"
      # Always force recreate so "hot update" restarts the service even if the
      # image id did not change (local bind mounts / same digest).
      compose up -d --force-recreate --remove-orphans "$SERVICE" 2>&1
      echo ">>> docker compose ps ${SERVICE}"
      compose ps "$SERVICE" 2>&1
    } 2>&1
  )
  code=$?
  set -e
  msg=$(printf '%s' "$out" | tail -c 1800)
  if [[ $code -ne 0 ]]; then
    log "update failed (exit $code): $msg"
    write_status "error" "update failed (exit $code): $msg" "$tag" "$full"
    return "$code"
  fi
  log "update done: $full"
  write_status "done" "updated and restarted: ${full}" "$tag" "$full"
}

mkdir -p "$DATA_DIR"
log "watching ${REQ_FILE} (compose=${COMPOSE_DIR} service=${SERVICE} poll=${POLL_SEC}s use_ghcr=${USE_GHCR})"
while true; do
  if [[ -f "$REQ_FILE" ]]; then
    # Atomic claim to avoid double-run.
    if mv "$REQ_FILE" "${REQ_FILE}.running" 2>/dev/null; then
      run_update "${REQ_FILE}.running" || true
      rm -f "${REQ_FILE}.running" "$REQ_FILE"
    else
      # Fallback if mv fails (cross-fs): run in place then delete.
      run_update "$REQ_FILE" || true
      rm -f "$REQ_FILE"
    fi
  fi
  sleep "$POLL_SEC"
done
